### ISSUE TITLE
Add sponsors

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [rubyconfindia/rubyconfindia.github.io#3]
Add GoJek as Platinum sponsor and Josh as Gold sponsor cc @sahilbhatia

**Comment by sahilbhatia** [comment]
@prathamesh-sonpatki 

Committed changes to add sponsors: https://github.com/rubyconfindia/rubyconfindia.github.io/commit/67601d761d319424beda384abd9f70c6a9fb038f
